---
- name: Extract zipped file
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: ~/

- name: Start Modules
  become: true
  shell: npm install
    pm2 stop default
    pm2 start npm -- start
