---
- name: "copy artifact into the server"
  become: true
  copy:
    src: files/artifact.tar.gz
    dest: ~/

- name: extract zipped artifact and install dependancies
  become: true
  shell: |
    tar -xvzf ~/artifact.tar.gz

- name: Start Modules
  become: true
  shell: npm install
    sudo pm2 stop default
    sudo pm2 start ~/dist/main.js -f
